# Generated by Django 4.1 on 2022-08-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSAP.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rubro_empresa', models.CharField(max_length=200)),
                ('cant_trabajadores', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSAP.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SSAP.usuario')),
            ],
        ),
    ]
