# Generated by Django 3.2.8 on 2022-08-27 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SSAP.usuario')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'administrador',
            },
            bases=('SSAP.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SSAP.usuario')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rubro_empresa', models.CharField(max_length=200)),
                ('cant_trabajadores', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
            bases=('SSAP.usuario',),
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SSAP.usuario')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'profesional',
            },
            bases=('SSAP.usuario',),
        ),
    ]
