# Generated by Django 4.1 on 2022-09-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
