# Generated by Django 4.1 on 2022-09-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSAP', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='CLIENTE_rut',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='SSAP.cliente'),
            preserve_default=False,
        ),
    ]
