# Generated by Django 4.1 on 2022-08-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAP', '0003_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='xd',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
