# Generated by Django 4.1 on 2022-09-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAP', '0003_notificacion_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
