INSERT INTO "USUARIO"("CONTRASEÑA", TIPO, ID_COMUNA, DIRECCION) VALUES (1234, 'ADMINISTRADOR', 13101, 'Calle Falsa');
INSERT INTO "ADMINISTRADORES" VALUES (65,'11.222.333-4','Admin Default');


select * from capacitacion;